name: palestine_console
description: Print.color() to console in any platform, more features will be added later.
version: 0.0.7
homepage: https://github.com/msayed-net/PalestineDevelopers
repository: https://github.com/PalestineDevelopers/console
issue_tracker: https://github.com/PalestineDevelopers/console/issues
documentation: https://palestinedevelopers.github.io/website/docs/console

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.8.1
  test: ^1.16.0
